### ISSUE TITLE
NotSerializableException on DeletingFileInputStream class running under Tomcat.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jnash67/tableexport-for-vaadin#28]
```
What steps will reproduce the problem?
1. Use TableExport to generate and download xls file.

What is the expected output? What do you see instead?
System crashes with next output:

SEVERE: IOException while loading persisted sessions: 
java.io.WriteAbortedException: writing aborted; 
java.io.NotSerializableException: 
com.vaadin.addon.tableexport.DeletingFileInputStream
java.io.WriteAbortedException: writing aborted; 
java.io.NotSerializableException: 
com.vaadin.addon.tableexport.DeletingFileInputStream
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1964)
.....

What version of the product are you using? On what operating system?
Table export version: 1.3.0
OS: CentOS 

Please provide any additional information below.
I've fixed problem locally by using my own MyDeletingFileInputStream class with 
signature:

public class MyDeletingFileInputStream extends FileInputStream implements 
Serializable;


```

Original issue reported on code.google.com by `vitaly.r...@gmail.com` on 6 Aug 2012 at 2:47

**Comment by jnash67** [comment]
Made the inputstream transient
